<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Burnout Preventie Werkboek',
                'slug' => 'burnout-preventie-werkboek',
                'description' => 'Een uitgebreid werkboek om burnout te voorkomen en vroege signalen te herkennen. Met praktische oefeningen, zelftest en actieplan om stress beter te beheren en balans te vinden tussen werk en privé.',
                'short_description' => 'Voorkom burnout met dit praktische werkboek vol oefeningen en tools voor stressmanagement.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Werkboeken',
                'tags' => ['burnout', 'stress', 'werkboek', 'preventie'],
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now()->subDays(30),
                'file_size' => 2048000, // 2MB
                'file_type' => 'pdf',
                'download_count' => 127,
                'view_count' => 543,
                'sort_order' => 1,
            ],
            [
                'name' => 'Mindfulness Meditatie Gids',
                'slug' => 'mindfulness-meditatie-gids',
                'description' => 'Een complete gids voor het beoefenen van mindfulness meditatie. Inclusief audio-oefeningen, ademhalingstechnieken en dagelijkse meditaties voor meer rust en bewustzijn in je leven.',
                'short_description' => 'Leer mindfulness meditatie met deze complete gids inclusief praktische oefeningen.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Meditatie',
                'tags' => ['mindfulness', 'meditatie', 'ontspanning', 'bewustzijn'],
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now()->subDays(25),
                'file_size' => 1536000, // 1.5MB
                'file_type' => 'pdf',
                'download_count' => 89,
                'view_count' => 324,
                'sort_order' => 2,
            ],
            [
                'name' => 'Doelen Stellen Checklist',
                'slug' => 'doelen-stellen-checklist',
                'description' => 'Een praktische checklist om effectieve en haalbare doelen te stellen. Met SMART-doelen framework, actieplannen en voortgangsregistratie om je doelen daadwerkelijk te bereiken.',
                'short_description' => 'Stel effectieve doelen met deze stap-voor-stap checklist en actieplan.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Checklists',
                'tags' => ['doelen', 'planning', 'smart', 'actieplan'],
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now()->subDays(20),
                'file_size' => 512000, // 512KB
                'file_type' => 'pdf',
                'download_count' => 156,
                'view_count' => 432,
                'sort_order' => 3,
            ],
            [
                'name' => 'Loopbaan Oriëntatie Vragenlijst',
                'slug' => 'loopbaan-orientatie-vragenlijst',
                'description' => 'Een uitgebreide vragenlijst om je loopbaanwensen, waarden en motivaties in kaart te brengen. Inclusief analyse tool om je ideale carrièrepad te ontdekken en concrete stappen te bepalen.',
                'short_description' => 'Breng je loopbaanwensen in kaart met deze uitgebreide zelfanalyse vragenlijst.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Loopbaan',
                'tags' => ['loopbaan', 'carriere', 'zelfonderzoek', 'vragenlijst'],
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now()->subDays(15),
                'file_size' => 768000, // 768KB
                'file_type' => 'pdf',
                'download_count' => 73,
                'view_count' => 198,
                'sort_order' => 4,
            ],
            [
                'name' => 'Dagelijkse Reflectie Journal',
                'slug' => 'dagelijkse-reflectie-journal',
                'description' => 'Een 30-dagen reflectie journal om jezelf beter te leren kennen en bewuster te leven. Met dagelijkse prompts, dankbaarheidsoefeningen en ruimte voor persoonlijke inzichten en groei.',
                'short_description' => 'Ontwikkel een dagelijkse reflectiegewoonte met dit 30-dagen journal.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Journals',
                'tags' => ['reflectie', 'journal', 'dankbaarheid', 'zelfonderzoek'],
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now()->subDays(10),
                'file_size' => 1024000, // 1MB
                'file_type' => 'pdf',
                'download_count' => 94,
                'view_count' => 267,
                'sort_order' => 5,
            ],
            [
                'name' => 'Stress Management Toolkit',
                'slug' => 'stress-management-toolkit',
                'description' => 'Een complete toolkit met praktische technieken voor stressmanagement. Inclusief ademhalingsoefeningen, ontspanningstechnieken, timemanagement tips en noodhulp bij acute stress.',
                'short_description' => 'Beheer stress effectief met deze uitgebreide toolkit vol praktische technieken.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Toolkits',
                'tags' => ['stress', 'management', 'ontspanning', 'toolkit'],
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now()->subDays(8),
                'file_size' => 1792000, // 1.75MB
                'file_type' => 'pdf',
                'download_count' => 112,
                'view_count' => 389,
                'sort_order' => 6,
            ],
            [
                'name' => 'Werk-Privé Balans Planner',
                'slug' => 'werk-prive-balans-planner',
                'description' => 'Een praktische planner om je werk-privé balans te optimaliseren. Met tijd-audit, prioriteiten matrix en weekplanning om meer tijd te maken voor wat echt belangrijk is in je leven.',
                'short_description' => 'Creëer betere werk-privé balans met deze praktische planner en tijd-audit.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Planners',
                'tags' => ['balans', 'planning', 'tijd', 'prioriteiten'],
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now()->subDays(5),
                'file_size' => 896000, // 896KB
                'file_type' => 'pdf',
                'download_count' => 67,
                'view_count' => 145,
                'sort_order' => 7,
            ],
            [
                'name' => 'Zelfvertrouwen Booster Template',
                'slug' => 'zelfvertrouwen-booster-template',
                'description' => 'Een template om je zelfvertrouwen systematisch op te bouwen. Met affirmaties, succeservaringen tracker en oefeningen om beperkende gedachten om te zetten in krachtige overtuigingen.',
                'short_description' => 'Boost je zelfvertrouwen met dit template vol oefeningen en tracking tools.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Templates',
                'tags' => ['zelfvertrouwen', 'mindset', 'affirmaties', 'groei'],
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now()->subDays(3),
                'file_size' => 640000, // 640KB
                'file_type' => 'pdf',
                'download_count' => 45,
                'view_count' => 123,
                'sort_order' => 8,
            ],
            [
                'name' => 'Gewoonten Veranderen Stappenplan',
                'slug' => 'gewoonten-veranderen-stappenplan',
                'description' => 'Een wetenschappelijk onderbouwd stappenplan om slechte gewoonten te doorbreken en nieuwe, positieve gewoonten op te bouwen. Met habit tracker en motivatie tips voor duurzame verandering.',
                'short_description' => 'Verander je gewoonten blijvend met dit bewezen stappenplan en tracking systeem.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Stappenplannen',
                'tags' => ['gewoonten', 'verandering', 'discipline', 'tracking'],
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now()->subDays(1),
                'file_size' => 1152000, // 1.125MB
                'file_type' => 'pdf',
                'download_count' => 23,
                'view_count' => 87,
                'sort_order' => 9,
            ],
            [
                'name' => 'Persoonlijke Missie Statement Gids',
                'slug' => 'persoonlijke-missie-statement-gids',
                'description' => 'Een complete gids om je persoonlijke missie statement te ontwikkelen. Met waarden-exploratie, purpose-finding oefeningen en sjablonen om je levensdoel helder te krijgen.',
                'short_description' => 'Ontdek je levensmissie met deze gids vol waarden-oefeningen en templates.',
                'price' => 0.00,
                'original_price' => null,
                'is_free' => true,
                'category' => 'Gidsen',
                'tags' => ['missie', 'waarden', 'purpose', 'levensdoel'],
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'file_size' => 1408000, // 1.375MB
                'file_type' => 'pdf',
                'download_count' => 8,
                'view_count' => 34,
                'sort_order' => 10,
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}
